---
abstract: 'Retrieve information from X11 windows'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: X11-WindowHierarchy
requires:
  X11::Protocol: 0.56
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=X11-WindowHierarchy
  homepage: http://search.cpan.org/dist/X11-WindowHierarchy/
version: 0.001
